syntax = "proto3";

message Command {
  uint32 request_id = 1;

  oneof cmd {
    LedCommand led = 2;
    JoinCommand join = 3;
    OtaCommand ota = 4;
    TelCommand tel = 5;
    TelResponse tel_res = 6;
    DefaultImageCommand default_image = 7;
    ClearEpdCommand clear_epd = 8;
  }
}

message LedCommand {
  bytes mac = 1;
}
message DefaultImageCommand {
  bytes mac = 1;
}
message ClearEpdCommand {
  bytes mac = 1;
}
message JoinCommand {
  bytes mac = 1;
  bytes ots_mac = 2;
  uint64 obj_id = 3;

}
 
message OtaCommand {
  bytes mac = 1;
  bytes ots_mac = 2;
}

message TelCommand {
  bytes mac = 1;
}

message TelResponse {
  bytes mac = 1;
  string meta = 2;
}